#include "Clock_drv.h"
/*
 * SCG->SIRCCSR &= ~(SCG_SIRCCSR_SIRCEN_MASK);
	SCG->SIRCDIV |= (0x1 << SCG_SIRCDIV_SIRCDIV2_SHIFT); //enable 8Mhz
	SCG->SIRCCSR |= (SCG_SIRCCSR_SIRCEN_MASK);
	while(!(SCG->SIRCCSR & SCG_SIRCCSR_SIRCVLD_MASK));*/

void Clock_Init()
{
	SCG->SIRCCSR &= ~(SCG_SIRCCSR_SIRCEN_MASK);
	SCG->SIRCDIV |= (0x1 << SCG_SIRCDIV_SIRCDIV2_SHIFT); //enable 8Mhz
	SCG->SIRCCSR |= (SCG_SIRCCSR_SIRCEN_MASK);
	SCG->FIRCCSR &= ~(SCG_FIRCCSR_FIRCEN_MASK);
	SCG->FIRCDIV |= (0x1 << SCG_FIRCDIV_FIRCDIV2_SHIFT); //enable 8Mhz
	SCG->FIRCCSR |= (SCG_FIRCCSR_FIRCEN_MASK);
	while(!(SCG->SIRCCSR & SCG_SIRCCSR_SIRCVLD_MASK));
}
