#include "Port_drv.h"
void setup_pin()
{
	/*GPIO CONFIG*/
	PTD->PDDR |= (1<<STATUS_PIN);
	PTD->PDDR |= (1<<ADC_STATUS_PIN);
	/*PORT CLOCK CONFIG*/
	PCC->PCCn[STATUS_PIN_PORT_INDX] |= PCC_PCCn_CGC_MASK;
	PCC->PCCn[I2C0_PIN_PORT_INDX] |= PCC_PCCn_CGC_MASK;
	PCC->PCCn[ADC_PIN_PORT_INDX] |= PCC_PCCn_CGC_MASK;
	PCC->PCCn[ADC_STATUS_PIN_PORT_INDX] |= PCC_PCCn_CGC_MASK;
	/*MUX CONFIG*/
	ADC_PIN_PORT->PCR[ADC_PIN] &= ~(PORT_PCR_MUX_MASK);
	ADC_PIN_PORT->PCR[ADC_PIN] |= (0x00 << PORT_PCR_MUX_SHIFT);

	I2C0_PIN_PORT->PCR[SCL_PIN] &= ~(PORT_PCR_MUX_MASK);
	I2C0_PIN_PORT->PCR[SCL_PIN] |= (0x03 << PORT_PCR_MUX_SHIFT);
	I2C0_PIN_PORT->PCR[SCL_PIN] |= (0x03);

	I2C0_PIN_PORT->PCR[SDA_PIN] &= ~(PORT_PCR_MUX_MASK);
	I2C0_PIN_PORT->PCR[SDA_PIN] |= (0x03 << PORT_PCR_MUX_SHIFT);
	I2C0_PIN_PORT->PCR[SDA_PIN] |= (0x03);

	STATUS_PIN_PORT->PCR[STATUS_PIN] &= ~(PORT_PCR_MUX_MASK);
	STATUS_PIN_PORT->PCR[STATUS_PIN] |= (0x01 << PORT_PCR_MUX_SHIFT);

	STATUS_PIN_PORT->PCR[ADC_STATUS_PIN] &= ~(PORT_PCR_MUX_MASK);
	STATUS_PIN_PORT->PCR[ADC_STATUS_PIN] |= (0x01 << PORT_PCR_MUX_SHIFT);
}
void pin_set(GPIO_Type* GPIOx, uint32_t pin_number)
{
	GPIOx->PSOR = (1 << pin_number);
}
void pin_clear(GPIO_Type* GPIOx, uint32_t pin_number)
{
	GPIOx->PCOR = (1 << pin_number);
}
void pin_toggle(GPIO_Type* GPIOx, uint32_t pin_number)
{
	GPIOx->PTOR = (1 << pin_number);
}
